### PR TITLE
chore: head support

### PR DESCRIPTION
**Pull request by sppatel**
Turbo repo introduce support for `dry-run` to inspect caches and report on whether a cache entry in the local and/or remote cache exists for a given hash.   In order to leverage, remote cache implementors must implement a HEAD route to check for the resource.  This PR enables this.

See the following for references..

https://github.com/vercel/turborepo/issues/1437
https://github.com/vercel/turborepo/pull/1988

and this article for use cases on leveraging this new info reported by dry-run.

https://medium.com/@sppatel/maximizing-job-parallelization-in-ci-workflows-with-jest-and-turborepo-da86b9be0ee6

### CODE REVIEW

**Comment by fox1t** [comment]
Thanks for opening the PR!
One question: aren't HEAD and GET the same thing besides the VERB? If so, we can reuse the same route defined for GET and add the HEAD verb to it.
Also, would you mind adding tests?

**Comment by sppatel** [comment]
> 



> Thanks for opening the PR! One question: aren't HEAD and GET the same thing besides the VERB? If so, we can reuse the same route defined for GET and add the HEAD verb to it. Also, would you mind adding tests?

They are different because HEAD should not return back a response payload.   So the implementation should only check for the existence of the resource and not try to retrive/return it.  Yes - I will add tests.

**Comment by sppatel** [comment]
@fox1t I've pushed tests but none of the tests pass locally for me (mabye configuration issues but not clear how to setup my env to be able to run locally) - would you mind re-kicking the build and see if we're good?

**Review by fox1t — APPROVED** [review]
LGTM

**Comment by sppatel** [comment]
@tehKapa / @fox1t any chance we can cut a release for this - looking to deploy it ASAP.

**Comment by tehKapa** [comment]
> @tehKapa / @fox1t any chance we can cut a release for this - looking to deploy it ASAP.

Done.

**Pull request merged**
