### PR TITLE
Add linux/arm64 docker image support

### PR DESCRIPTION
**Pull request by joedevivo**

### CODE REVIEW

**Comment by fox1t** [comment]
Is `TARGETPLATFORM` a predefined build env var?

**Comment by fox1t** [comment]
> Is `TARGETPLATFORM` a predefined build env var?

Reference: https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope

**Comment by tehKapa** [comment]
@joedevivo, thank you for your contribution. Could you commit using Conventional Commits? thank you https://github.com/ducktors/turborepo-remote-cache#how-to-commit

**Comment by tehKapa** [comment]
@all-contributors add @joedevivo for infra

**Pull request merged**
