### PR TITLE
feat: how to run in aws lambda

### PR DESCRIPTION
**Pull request by tom-fletcher**
## In this PR:

A guide on how to run the `turborepo-remote-cache` server in an AWS Lambda Function.

Credit to @cpitt for a starting point on the handler code in #28.

This is dependant on #86 - as this change is required to allow the Lambda's temporary credentials to access the S3 bucket.

## Issues reference:
 - #28

### CODE REVIEW

**Comment by fox1t** [comment]
This is amazing. I think we can make it even easier! Would you mind adding a new entry point for the application inside `/src` folder? The same as we did for Vercel which has its own `vercel.ts`. At that point, there will be no need to force users to write their own Lambda proxy logic..

**Comment by tehKapa** [comment]
@all-contributors add @tom-fletcher for docs

**Comment by tehKapa** [comment]
@all-contributors add @tom-fletcher for doc

**Comment by tom-fletcher** [comment]
@fox1t I'll have a look at this tomorrow my time. Vercel is a lot more graceful - with Lamba there is no remote build step (so there will always have to be some handler code manually written), but perhaps the logic can be moved into the library so it looks something like this:

```js
import { lambdaHandler } from 'turborepo-remote-cache';

export const handler = lambdaHandler;
```

**Comment by tom-fletcher** [comment]
Following changes have been made:

- Moved the "Running in AWS Lambda" docs to live under "Deployment environments" as this is more consistent with existing docs
- Moved the logic for the AWS Lambda Function into `src/aws-lambda.ts` and updated the docs. I've also added an example of how to create a bundle with `esbuild` to help get anyone who hasn't done this before started

While I was there, I also added an additional update to the docs to include information on how to use local environment variables to configure `turbo`, as an alternative to adding a `config.json`. I thought it easier to include in this PR, so it all can be reviewed in one go.

Using these env vars can be useful if you don't want to hard-code your `apiUrl` (for example if this is has been provisioned from an IaC provider such as Terraform or Pulumi), and want to pass configuration in via GitHub Actions or Codespaces secrets.

**Review by fox1t — APPROVED** [review]
LGTM

**Pull request merged**
