### PR TITLE
fix(docs): use recommended docker config for remote cache

### PR DESCRIPTION
**Pull request by gustavoam-asdf**
## In this PR:

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## Issues reference:
 - https://github.com/ducktors/turborepo-remote-cache/issues/
 - https://github.com/ducktors/turborepo-remote-cache/issues/

### Checklist:

* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/ducktors/turborepo-remote-cache/pulls) for the same update/change?

* [ ] Have you lint your code with `pnpm lint` locally prior to submission?
* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran build with `pnpm build` of your changes locally?
* [ ] Have you successfully ran tests with `pnpm test` of your changes locally?
* [ ] Have you commit using [Conventional Commits](https://github.com/ducktors/turborepo-remote-cache#how-to-commit)?

### CODE REVIEW

**Comment by gustavoam-asdf** [comment]
Use recomended config of [turbo repo](https://turbo.build/repo/docs/handbook/deploying-with-docker#remote-caching)

**Comment by fox1t** [comment]
LGTM

**Review by fox1t — APPROVED** [review]

**Comment by matteovivona** [comment]
@all-contributors add @gustavoam-asdf doc

**Comment by gtjamesa** [comment]
Just FYI, the turbo docs recommend including the git directory

https://turbo.build/repo/docs/core-concepts/caching/file-inputs#turborepos-default-behavior

**Pull request merged**
