### PR TITLE
Add readonly mode

### PR DESCRIPTION
**Pull request by maschwenk**
## In this PR:

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## Issues reference:
 - https://github.com/ducktors/turborepo-remote-cache/issues/
 - https://github.com/ducktors/turborepo-remote-cache/issues/

### Checklist:

* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/ducktors/turborepo-remote-cache/pulls) for the same update/change?

* [ ] Have you lint your code with `pnpm lint` locally prior to submission?
* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran build with `pnpm build` of your changes locally?
* [ ] Have you successfully ran tests with `pnpm test` of your changes locally?
* [ ] Have you commit using [Conventional Commits](https://github.com/ducktors/turborepo-remote-cache#how-to-commit)?

### CODE REVIEW

**Comment by matteovivona** [comment]
@maschwenk Could you follow the [conventional commits](https://github.com/ducktors/turborepo-remote-cache#how-to-commit)? Thanks!

**Comment by maschwenk** [comment]
> @maschwenk Could you follow the [conventional commits](https://github.com/ducktors/turborepo-remote-cache#how-to-commit)? Thanks!

@matteovivona Totally, was just putting this here as a placeholder as I wasn't sure if this was an idea y'all would be on board with at all

**Comment by maschwenk** [comment]
@matteovivona would you accept this PR more or less as-is? (after adding testings and conventional commits, obviously)

I opted to not mount the route at all because I want to make sure it 404s instead of 500s or 200s. I believe Turborepo will retry on 500s and 200 ACKing feels kinda wrong.

Worth noting I'm also working with Turborepo to implement this at the Client level, but they have some concerns about how to make that functionality coherent with all the other flags they have

- https://github.com/vercel/turbo/pull/6326

**Comment by maschwenk** [comment]
@fox1t agreed. The server-side implementation use-case seems a little more fringey.

**Pull request closed without merging**
