### PR TITLE
fix default path of local storage

### PR DESCRIPTION
**Pull request by PebblerWon**
if default value of  path is '', the TURBO_CACHE_FOLDER_NAME will not be used

### CODE REVIEW

**Comment by fox1t** [comment]
Thanks for the PR. Can you please fix the failing tests?

**Comment by tehKapa** [comment]
@all-contributors add @PebblerWon for code

**Comment by fox1t** [comment]
I think this is related to https://github.com/ducktors/turborepo-remote-cache/pull/67#issuecomment-1302538643

**Comment by fox1t** [comment]
@tm1000 what do you think about this issue? I think it should be fixed by your PR.

**Comment by tm1000** [comment]
@fox1t yes i think it does

**Comment by fox1t** [comment]
Superseded by https://github.com/ducktors/turborepo-remote-cache/pull/67

**Pull request closed without merging**
