### PR TITLE
Feat/Application Default Credentials GCP auth

### PR DESCRIPTION
**Pull request by emalihin**
From [docs](https://cloud.google.com/docs/authentication/application-default-credentials):

>ADC is a strategy used by [Cloud Client Libraries and Google API Client Libraries](https://cloud.google.com/apis/docs/client-libraries-explained) to automatically find credentials based on the application environment, and use those credentials to authenticate to Google Cloud APIs. When you set up ADC and use a client library, your code can run in either a development or production environment without changing how your application authenticates to Google Cloud services and APIs.

>    ADC searches for credentials in the following locations:
>    [GOOGLE_APPLICATION_CREDENTIALS environment variable](https://cloud.google.com/docs/authentication/application-default-credentials#GAC)
>    [User credentials set up with the Google Cloud CLI](https://cloud.google.com/docs/authentication/application-default-credentials#personal)
>    [The attached service account, as provided by the metadata server](https://cloud.google.com/docs/authentication/application-default-credentials#attached-sa)

By simply not providing credentials to Storage() constructor we instruct it to use one of the above three ADC methods. The 2nd and 3rd scenarios are most common in my experience - SDK knows where to find local credentials, and it will also check the GCP metadata server for the Service Account information (this is used for Workload Identity auth in GKE - the recommended way to authenticate with GCP. Very similar to AWS's IAM roles for service accounts/IRSA)

A slightly different approach to an existing PR https://github.com/ducktors/turborepo-remote-cache/pull/66:
*Use ADC if no explicit credentials were provided. Many tools that use GCP SDK follow this logic.

### CODE REVIEW

**Comment by fox1t** [comment]
Thanks for the PR and for explaining how it works.
Is it possible to add test cases for your additions?

**Comment by tehKapa** [comment]
@all-contributors add @emalihin for code

**Comment by emalihin** [comment]
> Is it possible to add test cases for your additions?

Tbh I am a bit lost as to how to test GCP Storage SDK in this project. I've pushed a commit (had to upgrade dotenv for env override to work), and welcome any suggestions if it can be done better 🙏

**Comment by emalihin** [comment]
i think covered new functionality with a test now

**Comment by fox1t** [comment]
Awesome! LGTM

**Review by fox1t — APPROVED** [review]

**Comment by emalihin** [comment]
@fox1t seems that images aren't built on release, mind pushing it? 🙏

**Pull request merged**
