### PR TITLE
fix: don't require AWS env vars

### PR DESCRIPTION
**Pull request by jgoz**
Same as #37 but with fallbacks for Vercel.

### CODE REVIEW

**Comment by fox1t** [comment]
As far as I can see this is a superset of that PR, right? Do we have any way to test this?

**Comment by jgoz** [comment]
@fox1t I didn't see an obvious way to test it without the tests devolving into "verify that the mocks have been mocked correctly". Happy to update this branch if you have an idea and can point me in the right direction.

**Comment by fox1t** [comment]
@jgoz, would you mind updating your branch so we can merge this?

**Comment by jgoz** [comment]
@fox1t  done

**Comment by tehKapa** [comment]
@all-contributors please add @jgoz for code

**Pull request merged**
