### PR TITLE
fix: update fastify and plugins to 5.0

### PR DESCRIPTION
**Pull request by thyming**
## In this PR:

- Updates to fastify and related dependencies to be on the latest release (5.0)

### Checklist:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/ducktors/turborepo-remote-cache/pulls) for the same update/change?

* [x] Have you lint your code with `pnpm lint` locally prior to submission?
* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran build with `pnpm build` of your changes locally?
* [x] Have you successfully ran tests with `pnpm test` of your changes locally?
* [x] Have you commit using [Conventional Commits](https://github.com/ducktors/turborepo-remote-cache#how-to-commit)?

### CODE REVIEW

**Comment by matteovivona** [comment]
@all-contributors add @thyming on code

**Review by matteovivona — APPROVED** [review]

**Comment by matteovivona** [comment]
@thyming could you change the commit type to `fix`? 
It's a dependency update, I know, but I would still like to create a patch to ensure that Fastify 5 does not carry any breaking changes.

**Comment by matteovivona** [comment]
@SocketSecurity ignore npm/thread-stream@3.1.0
@SocketSecurity ignore npm/safe-regex2@4.0.0
@SocketSecurity ignore npm/find-my-way@9.1.0

**Comment by thyming** [comment]
> @thyming could you change the commit type to `fix`? It's a dependency update, I know, but I would still like to create a patch to ensure that Fastify 5 does not carry any breaking changes.

you got it 👍

**Review by matteovivona — APPROVED** [review]

**Comment by matteovivona** [comment]
@thyming I tried to run the new version with fastify 5 but I keep getting this error 

```
/home/app/node/node_modules/.pnpm/@fastify+error@4.0.0/node_modules/@fastify/error/index.js:18
      return new FastifyError(...args)
             ^
FastifyError [Error]: logger options only accepts a configuration object.
    at FastifyError (/home/app/node/node_modules/.pnpm/@fastify+error@4.0.0/node_modules/@fastify/error/index.js:18:14)
    at createLogger (/home/app/node/node_modules/.pnpm/fastify@5.1.0/node_modules/fastify/lib/logger-factory.js:100:11)
    at fastify (/home/app/node/node_modules/.pnpm/fastify@5.1.0/node_modules/fastify/fastify.js:139:33)
    at createApp (/home/app/node/src/app.ts:11:15)
    at <anonymous> (/home/app/node/src/index.ts:6:13)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5) {
  code: 'FST_ERR_LOG_INVALID_LOGGER_CONFIG',
  statusCode: 500
}

Node.js v20.13.1
```

any clue?

**Comment by thyming** [comment]
@matteovivona i can't reproduce...any chance you need to build?

**Pull request merged**
